---
- name: "Automation / Ansible / Node / Initialize / Discover Target Platform"
  ansible.builtin.setup:
    gather_subset: "min"
    gather_timeout: "5"

- name: "Automation / Ansible / Node / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in auto_ansible_node_platforms

- name: "Automation / Ansible / Node / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"
...
