---
- name: "Automation / Ansible / Node / Deploy / Tools"
  ansible.builtin.include_tasks:
    file: "auto_ansible_node_deploy_tools.yml"

- name: "Automation / Ansible / Node / Deploy / Python"
  ansible.builtin.include_tasks:
    file: "{{ 'auto_ansible_node_deploy_python-' + auto_ansible_node_os_family + '.yml' }}"
  when:
    - auto_ansible_node['bootstrap'] is defined
    - auto_ansible_node['bootstrap']
...
