---
- name: "Automation / Ansible / Node / Provision / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - auto_ansible_node_user is defined
      - auto_ansible_node_user['name'] is defined
      - auto_ansible_node_user['group'] is defined
      - auto_ansible_node_user['home'] is defined

- name: "Automation / Ansible / Node / Prepare / User"
  ansible.builtin.include_tasks:
    file: "auto_ansible_node_prepare_user.yml"

- name: "Automation / Ansible / Node / Prepare / Sudoers"
  ansible.builtin.include_tasks:
    file: "auto_ansible_node_prepare_sudoers.yml"
...
