---
- name: "Automation / Ansible / Control / Initialize"
  ansible.builtin.include_tasks:
    file: "auto_ansible_control_initialize.yml"

- name: "Automation / Ansible / Control / Prepare"
  ansible.builtin.include_tasks:
    file: "auto_ansible_control_prepare.yml"
  when:
    - "'prepare' in auto_ansible_control"
    - auto_ansible_control['prepare']

- name: "Automation / Ansible / Control / Setup"
  ansible.builtin.include_tasks:
    file: "auto_ansible_control_setup.yml"
  when:
    - "'setup' in auto_ansible_control"
    - auto_ansible_control['setup']

- name: "Automation / Ansible / Control / Provision"
  ansible.builtin.include_tasks:
    file: "auto_ansible_control_provision.yml"
  when:
    - "'provision' in auto_ansible_control"
    - auto_ansible_control['provision']

- name: "Automation / Ansible / Control / Finalize"
  ansible.builtin.include_tasks:
    file: "auto_ansible_control_finalize.yml"
...
