---
- name: "Manage Ansible Control Node"
  hosts: "ansible_control_nodes"
  gather_facts: false

  pre_tasks:

    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

  tasks:

    - name: "Register Managed Nodes in A:Platform64"
      vars:
        auto_ansible_control:
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_ansible_control"

- name: "Manage Ansible Managed Nodes"
  hosts: "ansible_managed_nodes"
  gather_facts: false

  pre_tasks:

    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

  tasks:

    - name: "Prepare ansible environment"
      vars:
        auto_ansible_node:
          prepare: true
          deploy: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_ansible_node"

    - name: "Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"
...
