---
- name: "Manage Ansible Control Node"
  hosts: "aplatform64_servers"
  gather_facts: false

  pre_tasks:

    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

  tasks:

    - name: "Setup A:Platform64"
      vars:
        auto_aplatform64:
          prepare: true
          setup: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_aplatform64"
...
