---
- name: "Manage A:Platform control node"
  hosts: "{{ auto_aplatform64_bootstrap | default( 'aplatform64_servers' ) }}"
  gather_facts: false

  pre_tasks:
    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

  tasks:
    - name: "Provision A:Platform64"
      vars:
        auto_aplatform64:
          prepare: true
          setup: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_aplatform64"
...
