---
namespace: "serdigital64"
name: "automation"
version: "3.1.0"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for managing automation tools provisioning"
license:
  - "Apache-2.0"
tags:
  - "automation"
  - "system"
  - "devops"
dependencies:
  serdigital64.application: "*"
  serdigital64.backup: "*"
  serdigital64.system: "*"
  serdigital64.security: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
