---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load Role variables auto_ansible_control"
      vars:
        auto_ansible_control_site: "{{ test_site }}"
        auto_ansible_control_users: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
        auto_ansible_control_managed: "{{ test_control_managed }}"
      ansible.builtin.include_role:
        public: true
        name: "auto_ansible_control"

    - name: "Load role variables auto_aplatform64"
      vars:
        auto_ansible_control_site: "{{ test_site }}"
        auto_ansible_control_users: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
        auto_ansible_control_managed: "{{ test_control_managed }}"
      ansible.builtin.include_role:
        public: true
        name: "auto_aplatform64"

    - name: "Discover path: inventory"
      ansible.builtin.stat:
        get_checksum: false
        follow: false
        get_mime: false
        get_attributes: false
        path: "{{ auto_aplatform64_base['files']['ansible_site_yml'] }}"
      register: test_path_stats

    - name: "Verify the file was created ({{ auto_aplatform64_base['files']['ansible_site_yml'] }})"
      ansible.builtin.assert:
        that:
          - test_path_stats['stat']['exists']
...
