---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision SSH"
      vars:
        auto_ansible_node:
          provision: true
        auto_ansible_node_user:
          name: "amnode"
          group: "amnode"
          home: "/home/amnode"
          description: "Ansible managed node"
          control_key: "{{
            lookup('env', 'APLATFORM64_ROOT') +
            '/collections/serdigital64/automation/roles/auto_ansible_node/molecule/resources/test-key-rsa.pub'
          }}"
      ansible.builtin.include_role:
        name: "auto_ansible_node"
...
