---
- name: "Automation / A:Platform64 / Provision / Playbooks / Publish playbooks ({{
    auto_ansible_control_base['paths']['site_playbooks'] }})"
  become: true
  ansible.builtin.copy:
    backup: false
    follow: false
    force: true
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{
      auto_aplatform64_base['paths']['playbooks'] + '/' +
      auto_aplatform64___provision_playbook['playbook'] + '.yml'
      }}"
    dest: "{{ auto_ansible_control_base['paths']['site_playbooks'] }}"
  loop: "{{ auto_aplatform64_playbooks }}"
  loop_control:
    loop_var: "auto_aplatform64___provision_playbook"

- name: "Automation / A:Platform64 / Provision / Playbooks / Create catalog ({{
    auto_aplatform64_base['files']['catalog_csv'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_aplatform64_base['templates']['catalog_csv'] }}"
    dest: "{{ auto_aplatform64_base['files']['catalog_csv'] }}"
...
