---
- name: "Automation / Aplatform64 / Setup / Module / Create site specific A:Platform64 settings ({{
    auto_aplatform64_base['files']['auto_aplatform64_yml'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_aplatform64_base['templates']['auto_aplatform64_yml'] }}"
    dest: "{{ auto_aplatform64_base['files']['auto_aplatform64_yml'] }}"

- name: "Automation / Aplatform64 / Setup / Module / Create A:Platform64 shell environment loader ({{
    auto_aplatform64_base['files']['aplatform64_env'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_aplatform64_base['templates']['aplatform64_env'] }}"
    dest: "{{ auto_aplatform64_base['files']['aplatform64_env'] }}"
...
