---
auto_ansible_node_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

auto_ansible_node_base:
  paths:
    ssh: "{{ auto_ansible_node_user['home'] + '/.ssh' }}"
    home: "{{ auto_ansible_node_user['home'] }}"
  run:
    visudo: "/usr/sbin/visudo"
  files:
    sudoers: "/etc/sudoers"
    authorized_keys: "{{ auto_ansible_node_user['home'] + '/.ssh/authorized_keys' }}"

auto_ansible_node_privilege: "ALL=(ALL) NOPASSWD: ALL"

# auto_ansible_node___path: ~
...
