---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create test site"
      vars:
        auto_ansible_control:
          resolve_prereq: true
          prepare: true
          setup: true
        auto_ansible_control_site: "{{ test_site }}"
        auto_ansible_control_owners: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
        auto_ansible_control_managed: "{{ test_control_managed }}"
      ansible.builtin.include_role:
        name: "auto_ansible_control"
        public: true

    - name: "Prepare"
      vars:
        auto_aplatform64:
          prepare: true
        auto_ansible_control_site: "{{ test_site }}"
        auto_ansible_control_owners: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
        auto_ansible_control_managed: "{{ test_control_managed }}"
      ansible.builtin.include_role:
        name: "auto_aplatform64"
...
