---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Register node"
      vars:
        auto_ansible_control:
          provision: true
        auto_ansible_control_managed: "{{ test_managed_host }}"
      ansible.builtin.include_role:
        name: "auto_ansible_control"
...
