---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "auto_ansible_control"

    - name: "Discover path: known_hosts"
      ansible.builtin.stat:
        get_checksum: false
        follow: false
        get_mime: false
        get_attributes: false
        path: "{{ auto_ansible_control_base['files']['known_hosts'] }}"
      register: test_path_stats

    - name: "Verify known_hosts was created"
      ansible.builtin.assert:
        that:
          - test_path_stats['stat']['exists']
          - test_path_stats['stat']['size'] > 0
...
