---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare node"
      vars:
        auto_ansible_node:
          prepare: true
        auto_ansible_node_user:
          name: "amnode"
          group: "amnode"
          home: "/home/amnode"
          description: "Ansible managed node"
      ansible.builtin.include_role:
        name: "auto_ansible_node"
...
