---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      vars:
        auto_ansible_control_users: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
      ansible.builtin.include_role:
        public: true
        name: "auto_ansible_control"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - auto_ansible_control_platforms is defined
          - auto_ansible_control_base is defined

    - name: "Verify defaults"
      ansible.builtin.assert:
        that:
          - auto_ansible_control_site is defined
          - auto_ansible_control_python is defined
          - auto_ansible_control_users['control']['name'] is defined
          - auto_ansible_control_users['control']['home'] is defined
          - auto_ansible_control_paths['root'] is defined
          - auto_ansible_control_paths['var'] is defined
...
